#!/bin/bash
clear
echo -e "\e[92mWordpress URL SQL update"
echo -e "\e[94m--------------------------------------"
read -p "Old website address: " -e -i "localhost/" oldaddress
read -p "New website address: " newaddress
echo ""
echo -e "\e[92mSQL query:"
echo -e "\e[94m--------------------------------------"
echo -e "\e[37mUPDATE wp_options SET option_value = replace(option_value, '$oldaddress', '$newaddress') WHERE option_name = 'home' OR option_name = 'siteurl';"
echo "UPDATE wp_posts SET guid = replace(guid, '$oldaddress','$newaddress');"
echo "UPDATE wp_posts SET post_content = replace(post_content, '$oldaddress', '$newaddress');"
echo "UPDATE wp_postmeta SET meta_value = replace(meta_value,'$oldaddress','$newaddress');"
echo ""
echo -e "\e[94mPress any key to quit."
read -n 1 -s -r
echo -e "\e[97m"
